version: '2.1'
services:
  #variWriter:
  #  build: .
  #  privileged: true
  #  environment:
  #    - MY_VARIABLE=
  #    - ANOTHER_VARIABLE=
  #  restart: no
  #  labels:
  #    io.balena.features.balena-api: 1
  #    io.balena.features.dbus: 1
  #  volumes:
  #    - var:/var/lib/balena
  #    - balena:~/.balena
  #  network_mode: host
  tester:
    build: ./tester
    privileged: true
    restart: no
    labels:
      io.balena.features.balena-api: 1
      io.balena.features.dbus: 1
    network_mode: host
    volumes:
      - var:/var/lib/balena
      - balena:~/.balena
volumes:
  balena:
  var: